export const CONFIG = {
  WORLD_WIDTH: 4000,
  WORLD_HEIGHT: 4000,
  FPS_LIMIT: 120,
  BLOOM_SCALE: 0.25,
  GRID_CELL_SIZE: 400,
  INITIAL_FOOD_COUNT: 50,
  INITIAL_ENEMY_COUNT: 20,
  PLAYER_LIVES: 5,
  PLAYER_BASE_SPEED: 110,
  ENEMY_BASE_SPEED: 85,
  WARP_MESSAGE_DURATION: 3000,
  KILL_QUOTA: 100,
  COLORS: {
    PLAYER: "#00ff88",
    ENEMY: "#ff4444",
    FOOD: "#ff0",
    BULLET: "#fff",
    BEAM: "#ff00ff",
    CHOOSE_MODE_TOUCH: "#00ff88",
    CHOOSE_MODE_KEYBOARD: "#00d4ff",
    CHOOSE_MODE_KEYBOARD_FIRE: "#ff00ff",
    ZOOM_COLOR: "#ff8500",
  },
};

export const GAME_STATES = {
  INITIAL: "INITIAL",
  PLAYING: "PLAYING",
  PAUSED: "PAUSED",
  GAME_OVER: "GAME_OVER",
};
